development:
  host: ldap.rdu.redhat.com
  port: 389
  base: dc=redhat,dc=com

test:
  host: ldap.for.your.domain.com
  port: 389
  base: dc=domain,dc=com

production:
  host: ldap.for.your.domain.com
  port: 389
  base: dc=domain,dc=com
